version: "4.0"
services:
  dev:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
  
  mongo:
    image: mongo:latest
  
  # Separate databases for each service
  mongo-books:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: books
    ports:
      - "27018:27017"
  
  mongo-warehouse:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: warehouse
    ports:
      - "27019:27017"
  
  mongo-orders:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: orders
    ports:
      - "27020:27017"
  
  api-books:
    build: ./api-books
    ports:
      - "3001:3000"
    depends_on:
      - mongo-books
  
  api-warehouse:
    build: ./api-warehouse
    ports:
      - "3002:3000"
    depends_on:
      - mongo-warehouse
  
  api-orders:
    build: ./api-orders
    ports:
      - "3003:3000"
    depends_on:
      - mongo-orders
  
  api-swagger:
    build: ./api-swagger
    ports:
      - "3004:3000"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"